SELECT * WHERE {
  BIND (STR(?a) AS ?str)
  BIND (LANG(?a) AS ?lang)
  FILTER (LANGMATCHES(?lang, "en"))
  BIND (LANGDIR(?a) AS ?langdir)
  BIND (DATATYPE(?a) AS ?datatype)
  FILTER (BOUND(?a))
  BIND (IRI("http://example.org/") AS ?iri)
  BIND (URI("http://example.org/") AS ?uri)
  BIND (BNODE(?a) AS ?bnode1)
  BIND (BNODE() AS ?bnode2)
  BIND (RAND() AS ?rand)
  BIND (ABS(?n) AS ?abs)
  BIND (CEIL(?n) AS ?ceil)
  BIND (FLOOR(?n) AS ?floor)
  BIND (ROUND(?n) AS ?round)
  BIND (CONCAT(?a, ?b, "c") AS ?concat)
  BIND (SUBSTR(?a, 1) AS ?substr1)
  BIND (SUBSTR(?a, 1, 2) AS ?substr2)
  BIND (STRLEN(?a) AS ?strlen)
  BIND (REPLACE(?a, "a", "b") AS ?replace1)
  BIND (REPLACE(?a, "a", "b", "i") AS ?replace2)
  BIND (UCASE(?a) AS ?ucase)
  BIND (LCASE(?a) AS ?lcase)
  BIND (ENCODE_FOR_URI(?a) AS ?encoded)
  FILTER (CONTAINS(?a, "b"))
  FILTER (STRSTARTS(?a, "b"))
  FILTER (STRENDS(?a, "b"))
  BIND (STRBEFORE(?a, "b") AS ?before)
  BIND (STRAFTER(?a, "b") AS ?after)
  BIND (YEAR(?date) AS ?year)
  BIND (MONTH(?date) AS ?month)
  BIND (DAY(?date) AS ?day)
  BIND (HOURS(?date) AS ?hours)
  BIND (MINUTES(?date) AS ?minutes)
  BIND (SECONDS(?date) AS ?seconds)
  BIND (TIMEZONE(?date) AS ?timezone)
  BIND (TZ(?date) AS ?tz)
  BIND (NOW() AS ?now)
  BIND (UUID() AS ?uuid)
  BIND (STRUUID() AS ?struuid)
  BIND (MD5(?a) AS ?md5)
  BIND (SHA1(?a) AS ?sha1)
  BIND (SHA256(?a) AS ?sha256)
  BIND (SHA384(?a) AS ?sha384)
  BIND (SHA512(?a) AS ?sha512)
  BIND (COALESCE(?a, ?b, 0) AS ?coalesce)
  BIND (IF(?a > 1, "yes", "no") AS ?if)
  BIND (STRLANG(?a, "en") AS ?strlang)
  BIND (STRLANGDIR(?a, "en", "ltr") AS ?strlangdir)
  BIND (STRDT(?a, <http://www.w3.org/2001/XMLSchema#string>) AS ?strdt)
  FILTER (SAMETERM(?a, ?b))
  FILTER (ISIRI(?a))
  FILTER (ISURI(?a))
  FILTER (ISBLANK(?a))
  FILTER (ISLITERAL(?a))
  FILTER (ISNUMERIC(?a))
  FILTER (hasLANG(?a))
  FILTER (hasLANGDIR(?a))
  FILTER (REGEX(?a, "^b"))
  FILTER (REGEX(?a, "^b", "i"))
  FILTER (EXISTS {
    ?a ?b ?c
  })
  FILTER (NOT EXISTS {
    ?a ?b ?c
  })
  FILTER (isTRIPLE(?t))
  BIND (TRIPLE(?a, ?b, ?c) AS ?triple)
  BIND (SUBJECT(?t) AS ?subject)
  BIND (PREDICATE(?t) AS ?predicate)
  BIND (OBJECT(?t) AS ?object)
  BIND (COUNT(DISTINCT ?a) AS ?count)
}
