FROM debian
FROM node:22-bookworm-slim@sha256:157c7ea6f8c30b630d6f0d892c4f961eab9f878e88f43dd1c00514f95ceded8a AS build-editor

RUN apt update -y
COPY ./editor /src
WORKDIR /src
RUN npm install
RUN npm run build

FROM node:22-bookworm-slim@sha256:157c7ea6f8c30b630d6f0d892c4f961eab9f878e88f43dd1c00514f95ceded8a AS deploy
WORKDIR /deploy
COPY --from=build-editor /src/build/ ./build
COPY --from=build-editor /src/package.json .
COPY --from=build-editor /src/package-lock.json .
RUN npm ci --omit dev

CMD ["node", "build"]
