FROM debian
FROM node:22-bookworm-slim@sha256:88f44fbb06cc98e1451e4e015c122f84030ec55c603f753ed97b889db0bb8d4d AS build-editor

RUN apt update -y
COPY ./editor /src
WORKDIR /src
RUN npm install
RUN npm run build

FROM node:22-bookworm-slim@sha256:88f44fbb06cc98e1451e4e015c122f84030ec55c603f753ed97b889db0bb8d4d AS deploy
WORKDIR /deploy
COPY --from=build-editor /src/build/ ./build
COPY --from=build-editor /src/package.json .
COPY --from=build-editor /src/package-lock.json .
RUN npm ci --omit dev

CMD ["node", "build"]
