FROM debian
FROM node:22-bookworm-slim@sha256:42cf02458a7ebeef48cb0125efd4c60df1fcfba1b23c39b1148e924d4c285e17 AS build-editor

RUN apt update -y
COPY ./editor /src
WORKDIR /src
RUN npm install
RUN npm run build

FROM node:22-bookworm-slim@sha256:42cf02458a7ebeef48cb0125efd4c60df1fcfba1b23c39b1148e924d4c285e17 AS deploy
WORKDIR /deploy
COPY --from=build-editor /src/build/ ./build
COPY --from=build-editor /src/package.json .
COPY --from=build-editor /src/package-lock.json .
RUN npm ci --omit dev

CMD ["node", "build"]
