name: build-test-publish
run-name: ${{ github.actor }} is building, testing and publishing 🚀

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-and-test:
    name: 🏗️ build & test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: cargo build --release
      - name: cargo test
        run: cargo test --release

  publish-cratesio:
    name: 📦 Publish to crates.io
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: publish to crates.io
        run: cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
