name: GitHub Actions Demo
run-name: ${{ github.actor }} is building, testing and publishing 🚀

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Cache target dir
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: target/
          key: target-${{  github.run_number }}-${{ github.run_attempt }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: build release
        run: cargo build --release
      - name: test
        run: cargo test --release
  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    # if: 
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Restore cargo build
        uses: actions/cache/restore@v4
        with:
          path: target/
          key: target-${{  github.run_number }}-${{ github.run_attempt }}
      - run: ls
      - name: publish to crate.io
        run: cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
